server:
  port: 8081
spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/meu-realm
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  application:
    name: contas
  datasource:
    primario:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3308/primario?createDatabaseIfNotExist=true
      username: root
      password: admin123
    secundario:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3308/secundario?createDatabaseIfNotExist=true
      username: root
      password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
